### ISSUE TITLE
Replication section is unfinished

### ISSUE THREAD

**Issue by YawLighthouse** [Megafunk/MassSample#13]
Hello, first off the documentation information is incredible and extremely helpful thank you! I wanted to point out that the replication section is unfinished and ends mid sentence.

"5.2.7 MassReplication
Replication support for Mass! Other modules override UMassReplicatorBase to replicate stuff. Entities are given a separate Network ID that gets"

**Comment by vorixo** [comment]
Yes, we are aware, the doc is still it's very wip we'll get to it at some point. We are first working on covering the more important parts from MassEntify and MassGameplay.
