### ISSUE TITLE
Do All Processors Tick Excecute every frame by default?

### ISSUE THREAD

**Issue by OptimisticMonkey** [Megafunk/MassSample#16]
(First - thank you for creating this sample project - it is super helpful)

I noticed that the execute method is being run by most processors on every frame, even if nothing has been spawned.  Is this the intention?  The method is very fast - but seems like should be more of an opt in?

**Comment by Megafunk** [comment]
Yes, this is how most ECS libraries work. Processor ticking is the default! However, if the queries are empty they simply get passed over like you said.

Observers are the exception where they only execute when the action they observe occurs + the subsystem calls them.

I do agree that all systems executing even when you are certain a specific query will never be hit is a little bit weird. I think it might be possible to unregister processors from the dependency graph at runtime but I would not recommend doing it as the dependency graph takes a while to rebuild. I'll look into it later...

We will mention this in the docs somewhere to make it more clear soon!
