### ISSUE TITLE
Is there any way to add a tag using AssortedFragment?

### ISSUE THREAD

**Issue by OptimisticMonkey** [Megafunk/MassSample#18]
Would love to be able to add a BasicVisualization Tag  to a EntityConfig without requiring a c++ trait....

Seems like AssortedFragment supports Tags, but the slate drop down filter only shows Fragments?

**Comment by Megafunk** [comment]
Slapped in a "assorted tags" trait really fast. Assorted fragments has handling for tags but only has the MassFragment-derived structs listed.
