### ISSUE TITLE
built-in Mass farm example

### ISSUE THREAD

**Issue by Megafunk** [Megafunk/MassSample#20]
Mass has as little farm plot example built in that's a bit outdated (old naming standards). It seems like a great example though, so I think we should look in to getting it running!

- [x] working farm plot
- [ ] farm plot interaction
- [ ] farm plot documentation

**Comment by Fangrelle** [comment]
I saw that (`MassEntityTestSuite`) but didn't think it was working. Do you know what it does, if its just naming it looked like it has some good examples of how to connect things up correctly.

**Comment by Megafunk** [comment]
I got it going but I think it's kind of a rough example because everything is very hardcoded and it's huuuuge!. Maybe we will make our own tinier farm plot? I just used random editor meshes here. 
![image](https://user-images.githubusercontent.com/6806463/164965081-a4de8eed-9d50-4f2f-a3cb-4db527366dee.png)

**Comment by Megafunk** [comment]
It's back in Engine/Plugins/Runtime/MassEntity/Content/TestAssets/MassEntityFarmTest.umap!
