### ISSUE TITLE
Pluginfy the entire project

### ISSUE THREAD

**Issue by Megafunk** [Megafunk/MassSample#21]
Because Mass is so modular, it would make sense to let people easily just add this sample as  plugin (or two) instead of having it as a project if they intend to use the features we make. 

- [x] Convert project to plugin
- [ ] separate some useful code into modules (or even more plugins)
- [ ] editor only modules for content example section etc

**Comment by Starkium** [comment]
agreed, this would be highly desired

**Comment by Megafunk** [comment]
Moved all code to one plugin. I'll get around to moving the content soon and the editor specific module eventually

**Comment by Megafunk** [comment]
The vast majority of the content is now in a plugin, I guess I'll close this for now unless people would prefer going without the small wrapper uproject
