### ISSUE TITLE
Mass Entity Collision

### ISSUE THREAD

**Issue by wtiaw** [Megafunk/MassSample#29]
Can the Mass Entity has collision?

I try to change ISMC's CollisionProfileName to BlockAll (in MassVisualizationComponent.cpp) but it doesn't work.

**Comment by vorixo** [comment]
Hello @wtiaw 
Remember that entities are small unique identifiers that point to a combination of [fragments](https://github.com/Megafunk/MassSample#mass-fragments) and [tags](https://github.com/Megafunk/MassSample#mass-tags) in memory.

If your collision shape is shared across all your entities in your archetype, you could use a Shared Fragment to set your collision data and then engineer collision heuristics in your processors.

The other option you have is to employ real actors with colision for the lowest levels of LOD (using the set of LOD traits) and employ entities for distant objects. My main advice for this is to take a look at the Matrix demo.

Unfortunately adding collision is not a very naive request... But we'll try to ask Epic if it would be possible to offer in-house collisions for raw entities.

**Comment by wtiaw** [comment]
I successfully solved this problem with the following three steps：

(in MassVisualizationComponent.cpp)
1.Set ISMC's CollisionProfileName to BlockAll (in MassVisualizationComponent.cpp).
2.Set UE::MassRepresentation::GCallUpdateInstances to 0.
3.Before BatchUpdateInstancesTransforms, we shoule RecreatePhysicsState.

**Comment by wtiaw** [comment]
I successfully solved this problem with the following three steps:

 (in MassVisualizationComponent.cpp)
1.Set ISMC's CollisionProfileName to BlockAll .
2.Set UE::MassRepresentation::GCallUpdateInstances to 0.
3.Before BatchUpdateInstancesTransforms() call RecreatePhysicsState()。

**Comment by vorixo** [comment]
By @wtiaw 

> I successfully solved this problem with the following three steps：
> 
> (in MassVisualizationComponent.cpp)
> 1.Set ISMC's CollisionProfileName to BlockAll (in MassVisualizationComponent.cpp).
> 2.Set UE::MassRepresentation::GCallUpdateInstances to 0.
> 3.Before BatchUpdateInstancesTransforms, we shoule RecreatePhysicsState.

**Comment by vorixo** [comment]
> By @wtiaw
> 
> > I successfully solved this problem with the following three steps：
> > (in `MassVisualizationComponent.cpp`)
> > 
> > 1. Set ISMC's `CollisionProfileName` to `BlockAll`
> > 2. Set `UE::MassRepresentation::GCallUpdateInstances` to 0
> > 3. Before `BatchUpdateInstancesTransforms()` call `RecreatePhysicsState()`

As a side comment to @wtiaw post, we confirmed that this approach would tank down your game time, so be careful with it.
