### ISSUE TITLE
Mass Suggestions

### ISSUE THREAD

**Issue by zoombapup** [Megafunk/MassSample#30]
Can we have an API that allows me to use compute shaders on Mass Entities? Feels wrong to miss out on the ability to really scale up some of this using GPU resources.

**Comment by vorixo** [comment]
@zoombapup Answer from Epic:
> no plans, correct. Right now I'm the only person working on Mass and the backlog is pretty large, plus sending off stuff to GPU is not my wheelhouse, so unless we hire someone or poach from another team, or community implements this, GPU-side Mass won't happen (anytime soon anyway).
