### ISSUE TITLE
Passing per instance Material data from a Processor to Instanced Static Meshes.

### ISSUE THREAD

**Issue by PreyK** [Megafunk/MassSample#35]
Hello :)
In epic's [video overview of Mass](https://dev.epicgames.com/community/learning/talks-and-demos/37Oz/large-numbers-of-entities-with-mass-in-unreal-engine-5), there's a mention of the possibility to pass custom data to the entity's material.
I'm currently using my own homebrew ECS for my farming game where a lot of stuff needs to grow at once, I'm using a HISM with per-instance material data that controls the growth of the plants.
However, I'd love to just use mass instead, it has better performance than mine and I wouldn't have to maintain my own system.

On the [article with the video](https://dev.epicgames.com/community/learning/talks-and-demos/37Oz/large-numbers-of-entities-with-mass-in-unreal-engine-5) at the bottom of the page, there's a part about it
`It took me some tries to be able to send the Custom Data to the material from a Processor but in the end it was just a couple of lines of code.`
But no sample or any further explanation.

Does anyone have any ideas or insight on how to do this?
I'd love to contribute back a demo of this if I manage to get it working :)
Thanks for this repo btw, it was already a huge help.
And my apologies if it's off, haven't found anywhere else I could ask about this, hope it's okay but feel free to delete it if it isn't

![image](https://user-images.githubusercontent.com/1968543/177010178-c7090ee5-0d5d-497b-9ea1-4310b137cfa8.png)
![image](https://user-images.githubusercontent.com/1968543/177010174-48dcaa75-54d3-4f62-8b51-92f3d1e5ea2a.png)

**Comment by Megafunk** [comment]
Looks like `ISMInfo.AddBatchedCustomData<>()` is the ticket. The CitySample has quite a few uses of it for the crowd animation and traffic.

**Comment by PreyK** [comment]
Looked into the City Sample, managed to get it to work!
https://www.youtube.com/watch?v=nC-SskL4r9I
What confused me is that you only need to call `ISMInfo.AddBatchedCustomData(MyFragment.MyCustomData)` once from a `UMassObserverProcessor` at initialization.
From there on, you modify `MyFragment.MyCustomData` from anywhere, the modified custom data is automatically represented in the ISM, you don't need to explicitly update the ISM's custom data (looks like it's just a ref wich is quite amazing).
Will make a PR with a demo 👍

**Comment by Ji-Rath** [comment]
> Looked into the City Sample, managed to get it to work! https://www.youtube.com/watch?v=nC-SskL4r9I What confused me is that you only need to call `ISMInfo.AddBatchedCustomData(MyFragment.MyCustomData)` once from a `UMassObserverProcessor` at initialization. From there on, you modify `MyFragment.MyCustomData` from anywhere, the modified custom data is automatically represented in the ISM, you don't need to explicitly update the ISM's custom data (looks like it's just a ref wich is quite amazing). Will make a PR with a demo 👍

Really cool stuff! But I believe when you set a processor to 'bAutoRegisterWithProcessingPhases' it causes the observer to run every tick. Please correct me if I am wrong, that is just my observation.

**Comment by Megafunk** [comment]
Ack!!! You are right, Ji-Rath! It seems that you have to call `AddBatchedCustomData` every frame after all unless I am missing something. It appears the city sample does that as well.

**Comment by PreyK** [comment]
> > Looked into the City Sample, managed to get it to work! https://www.youtube.com/watch?v=nC-SskL4r9I What confused me is that you only need to call `ISMInfo.AddBatchedCustomData(MyFragment.MyCustomData)` once from a `UMassObserverProcessor` at initialization. From there on, you modify `MyFragment.MyCustomData` from anywhere, the modified custom data is automatically represented in the ISM, you don't need to explicitly update the ISM's custom data (looks like it's just a ref wich is quite amazing). Will make a PR with a demo 👍
> 
> Really cool stuff! But I believe when you set a processor to 'bAutoRegisterWithProcessingPhases' it causes the observer to run every tick. Please correct me if I am wrong, that is just my observation.

Are you sure?
Based on epic's video it shouldn't.

Setting `bAutoRegisterWithProcessingPhases` to true is the same as ticking it in your Project Settings -> Mass -> Processor CDOs or in your project's `DefaultMass.ini`
As far as I understand from epic's video it should just register that processor for its processing phase (automatically adds that processor to the world for the processing phase its valid)
https://youtu.be/f9q8A-9DvPo?t=492

![image](https://user-images.githubusercontent.com/1968543/178019443-eceae26f-922d-4274-8fc1-6a44e3901137.png)

Since it's an observer processor that "observes" `Operation = EMassObservedOperation::Add;` it should only run when entities are added?
![image](https://user-images.githubusercontent.com/1968543/178020446-07b76c27-7b87-4f15-902f-4fccc8ff1b0e.png)

Based on stuff I experimented with `AddBatchedCustomData` just adds a custom data pointer reinterpreted as floats.
(like ISM custom float data)
![image](https://user-images.githubusercontent.com/1968543/178021640-15180758-c9d9-46ff-a742-989147ac4e79.png)

Once we added it to the entity, in theory, we shouldn't need to touch it anymore but I'd definitely kill for some official documentation on this rn :D

**Comment by Megafunk** [comment]
MassObservers actually have `bAutoRegisterWithProcessingPhases` set to false in their parent class and are designed to be called only from the observer manager when their watched fragments are alerted to changes by things like deferred fragment adds, etc. By setting it to true your observer processor kind of just runs ever frame AND with observer changes.
