### ISSUE TITLE
Package Builds Fail to load with Plugin Enabled

### ISSUE THREAD

**Issue by Edstub207** [Megafunk/MassSample#45]
Hello!

We have an issue with the plugin being enabled, we've tested a couple of changes to try and get it working but had no luck. But whenever we build a package build (With the plugin enabled) it fails to launch with the following error:
![image](https://user-images.githubusercontent.com/13305475/183867672-2c7e08bf-5200-4957-a457-fc3decd164cc.png)

It's not super critical for us, but it would be nice to have the plugin enabled by default.

**Comment by Megafunk** [comment]
`	"EnabledByDefault": true,` is now in the .uplugin Not sure if this is exactly your issue. Perhaps my modules are set up poorly for non editor builds? I can try it out soon.

**Comment by Megafunk** [comment]
Gonna clean this one up, let me know if I made any other goofs
