### ISSUE TITLE
UE-5.0.3-Release Compile Error.

### ISSUE THREAD

**Issue by Checkmate** [Megafunk/MassSample#47]
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\MSSubsystem.h(21): error C2065: “FMassEntityManager”: 未声明的标识符
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\MSSubsystem.h(21): error C2923: "TSharedPtr": "FMassEntityManager" 不是参数 "ObjectType" 的有效 模板 类型参数
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\MSSubsystem.h(21): note: 参见“FMassEntityManager”的声明
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\MSSubsystem.h(21): error C2976: “TSharedPtr”: 模板 参数太少
1>E:\engine\Engine\Source\Runtime\Core\Public\Templates\SharedPointer.h(661): note: 参见“TSharedPtr”的声明
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\MSSubsystem.h(21): error C2955: “TSharedPtr”: 使用 类 模板 需要 模板 参数列表
1>E:\engine\Engine\Source\Runtime\Core\Public\Templates\SharedPointer.h(661): note: 参见“TSharedPtr”的声明
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\MSSubsystem.h(17): error C2512: “TSharedPtr”: 没有合适的默认构造函数可用
1>E:\engine\Engine\Source\Runtime\Core\Public\Templates\SharedPointer.h(661): note: 参见“TSharedPtr”的声明
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\MSSubsystem.h(36): error C2662: “void TSharedPtr<ObjectType,InMode>::Reset(void)”: 不能将“this”指针从“TSharedPtr”转换为“TSharedPtr<ObjectType,InMode> &”
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\MSSubsystem.h(36): note: 原因如下: 无法从“TSharedPtr”转换为“TSharedPtr<ObjectType,InMode>”
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\MSSubsystem.h(36): note: 转换要求第二个用户定义的转换运算符或构造函数
1>E:\engine\Engine\Source\Runtime\Core\Public\Templates\SharedPointer.h(1082): note: 参见“TSharedPtr<ObjectType,InMode>::Reset”的声明
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Experimental\MSEntityUtils.h(30): error C2061: 语法错误: 标识符“FMassEntityManager”
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Experimental\MSEntityUtils.h(39): error C2061: 语法错误: 标识符“FMassEntityManager”
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Experimental\MSEntityUtils.h(27): error C2664: “const FMassEntityTemplate *FMassEntityConfig::GetOrCreateEntityTemplate(AActor &,const UObject &) const”: 无法将参数 1 从“const UWorld”转换为“AActor &”
1>E:\engine\Engine\Plugins\Runtime\MassGameplay\Source\MassSpawner\Public\MassEntityConfigAsset.h(33): note: 参见“FMassEntityConfig::GetOrCreateEntityTemplate”的声明
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Experimental\MSEntityUtils.h(32): error C2065: “EntityManager”: 未声明的标识符
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Experimental\MSEntityUtils.h(42): error C2065: “EntitySubSystem”: 未声明的标识符
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Experimental\MSEntityUtils.h(43): error C2065: “EntitySubSystem”: 未声明的标识符
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(24): error C2065: “FMassEntityManager”: 未声明的标识符
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(24): error C2065: “EntitySubSystem”: 未声明的标识符
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(25): error C2039: "GetMutableEntityManager": 不是 "UMassEntitySubsystem" 的成员
1>E:\engine\Engine\Plugins\Runtime\MassGameplay\Source\MassSpawner\Public\MassEntityTemplateRegistry.h(14): note: 参见“UMassEntitySubsystem”的声明
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(42): error C2065: “EntitySubSystem”: 未声明的标识符
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(44): error C2065: “EntitySubSystem”: 未声明的标识符
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(60): error C2664: “const FMassEntityTemplate *FMassEntityConfig::GetOrCreateEntityTemplate(AActor &,const UObject &) const”: 无法将参数 1 从“UWorld”转换为“AActor &”
1>E:\engine\Engine\Plugins\Runtime\MassGameplay\Source\MassSpawner\Public\MassEntityConfigAsset.h(33): note: 参见“FMassEntityConfig::GetOrCreateEntityTemplate”的声明
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(60): error C2530: “EntityTemplate”: 必须初始化引用
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(63): error C2065: “FMassEntityManager”: 未声明的标识符
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(63): error C2065: “EntityManager”: 未声明的标识符
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(64): error C2039: "GetMutableEntityManager": 不是 "UMassEntitySubsystem" 的成员
1>E:\engine\Engine\Plugins\Runtime\MassGameplay\Source\MassSpawner\Public\MassEntityTemplateRegistry.h(14): note: 参见“UMassEntitySubsystem”的声明
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(96): error C2065: “EntityManager”: 未声明的标识符
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(99): error C2065: “EntityManager”: 未声明的标识符
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(99): error C2065: “FMassDeferredCreateCommand”: 未声明的标识符
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(99): error C2061: 语法错误: 标识符“FMassEntityManager”
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(101): error C2065: “EntityManager”: 未声明的标识符
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(102): error C2065: “EntityManager”: 未声明的标识符
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(106): error C2065: “EntityManager”: 未声明的标识符
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(109): error C2065: “EntityManager”: 未声明的标识符
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(112): error C2065: “EntityManager”: 未声明的标识符
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(113): error C2653: “FMassArchetypeEntityCollection”: 不是类或命名空间名称
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(113): error C2065: “NoDuplicates”: 未声明的标识符
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(113): error C3861: “FMassArchetypeEntityCollection”: 找不到标识符
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(126): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(126): error C2143: 语法错误: 缺少“;”(在“&”的前面)
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(126): error C2065: “EntitySubSystem”: 未声明的标识符
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(127): error C2039: "GetEntityManager": 不是 "UMassEntitySubsystem" 的成员
1>E:\engine\Engine\Plugins\Runtime\MassGameplay\Source\MassSpawner\Public\MassEntityTemplateRegistry.h(14): note: 参见“UMassEntitySubsystem”的声明
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(129): error C2065: “EntitySubSystem”: 未声明的标识符
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(132): error C2065: “EntitySubSystem”: 未声明的标识符
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(132): error C2065: “EntitySubSystem”: 未声明的标识符
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(136): error C2065: “EntitySubSystem”: 未声明的标识符
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(136): error C2737: “TransformFragment”: 必须初始化 const 对象
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(137): error C3536: “TransformFragment”: 初始化之前无法使用
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(147): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(147): error C2143: 语法错误: 缺少“;”(在“&”的前面)
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(147): error C2065: “EntitySubSystem”: 未声明的标识符
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(148): error C2039: "GetEntityManager": 不是 "UMassEntitySubsystem" 的成员
1>E:\engine\Engine\Plugins\Runtime\MassGameplay\Source\MassSpawner\Public\MassEntityTemplateRegistry.h(14): note: 参见“UMassEntitySubsystem”的声明
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(151): error C2065: “EntitySubSystem”: 未声明的标识符
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(151): error C2737: “CollisionQueryFragment”: 必须初始化 const 对象
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(152): error C3536: “CollisionQueryFragment”: 初始化之前无法使用
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(161): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(161): error C2143: 语法错误: 缺少“;”(在“&”的前面)
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(161): error C2065: “EntitySubSystem”: 未声明的标识符
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(162): error C2039: "GetEntityManager": 不是 "UMassEntitySubsystem" 的成员
1>E:\engine\Engine\Plugins\Runtime\MassGameplay\Source\MassSpawner\Public\MassEntityTemplateRegistry.h(14): note: 参见“UMassEntitySubsystem”的声明
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(165): error C2065: “EntitySubSystem”: 未声明的标识符
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(167): error C2065: “EntitySubSystem”: 未声明的标识符
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(167): error C2737: “TransformFragmentPtr”: 必须初始化 const 对象
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(167): error C3536: “TransformFragmentPtr”: 初始化之前无法使用
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(178): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(178): error C2143: 语法错误: 缺少“;”(在“&”的前面)
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(178): error C2065: “EntityManager”: 未声明的标识符
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(179): error C2039: "GetEntityManager": 不是 "UMassEntitySubsystem" 的成员
1>E:\engine\Engine\Plugins\Runtime\MassGameplay\Source\MassSpawner\Public\MassEntityTemplateRegistry.h(14): note: 参见“UMassEntitySubsystem”的声明
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(181): error C2065: “EntityManager”: 未声明的标识符
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(181): error C2065: “EntityManager”: 未声明的标识符
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(184): error C2065: “EntityManager”: 未声明的标识符
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(184): error C2737: “MassForceFragmentPtr”: 必须初始化 const 对象
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(184): error C3536: “MassForceFragmentPtr”: 初始化之前无法使用
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(199): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(199): error C2143: 语法错误: 缺少“;”(在“&”的前面)
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(199): error C2065: “EntityManager”: 未声明的标识符
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(200): error C2039: "GetEntityManager": 不是 "UMassEntitySubsystem" 的成员
1>E:\engine\Engine\Plugins\Runtime\MassGameplay\Source\MassSpawner\Public\MassEntityTemplateRegistry.h(14): note: 参见“UMassEntitySubsystem”的声明
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(207): error C2065: “EntityManager”: 未声明的标识符
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(209): error C2819: “FMassEntityHandle”类型没有重载成员“operator ->”
1>E:\engine\Engine\Plugins\Runtime\MassEntity\Source\MassEntity\Public\MassExecutor.h(12): note: 参见“FMassEntityHandle”的声明
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(209): note: 是否改用“.”?
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(209): error C2039: "GetTransform": 不是 "FMassEntityHandle" 的成员
1>E:\engine\Engine\Plugins\Runtime\MassEntity\Source\MassEntity\Public\MassExecutor.h(12): note: 参见“FMassEntityHandle”的声明
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(209): error C2039: "__this": 不是 "FMassEntityHandle" 的成员
1>E:\engine\Engine\Plugins\Runtime\MassEntity\Source\MassEntity\Public\MassExecutor.h(12): note: 参见“FMassEntityHandle”的声明
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(231): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(231): error C2143: 语法错误: 缺少“;”(在“&”的前面)
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(231): error C2065: “EntityManager”: 未声明的标识符
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(232): error C2039: "GetEntityManager": 不是 "UMassEntitySubsystem" 的成员
1>E:\engine\Engine\Plugins\Runtime\MassGameplay\Source\MassSpawner\Public\MassEntityTemplateRegistry.h(14): note: 参见“UMassEntitySubsystem”的声明
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(238): error C2065: “EntityManager”: 未声明的标识符
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(238): error C2819: “FMassEntityHandle”类型没有重载成员“operator ->”
1>E:\engine\Engine\Plugins\Runtime\MassEntity\Source\MassEntity\Public\MassExecutor.h(12): note: 参见“FMassEntityHandle”的声明
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(238): note: 是否改用“.”?
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(239): error C2039: "GetTransform": 不是 "FMassEntityHandle" 的成员
1>E:\engine\Engine\Plugins\Runtime\MassEntity\Source\MassEntity\Public\MassExecutor.h(12): note: 参见“FMassEntityHandle”的声明
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(239): error C2039: "__this": 不是 "FMassEntityHandle" 的成员
1>E:\engine\Engine\Plugins\Runtime\MassEntity\Source\MassEntity\Public\MassExecutor.h(12): note: 参见“FMassEntityHandle”的声明
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(259): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(259): error C2143: 语法错误: 缺少“;”(在“&”的前面)
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(259): error C2065: “EntityManager”: 未声明的标识符
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(260): error C2039: "GetEntityManager": 不是 "UMassEntitySubsystem" 的成员
1>E:\engine\Engine\Plugins\Runtime\MassGameplay\Source\MassSpawner\Public\MassEntityTemplateRegistry.h(14): note: 参见“UMassEntitySubsystem”的声明
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(280): error C2065: “EntityManager”: 未声明的标识符
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(305): error C4430: 缺少类型说明符 - 假定为 int。注意: C++ 不支持默认 int
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(305): error C2143: 语法错误: 缺少“;”(在“&”的前面)
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(305): error C2065: “EntityManager”: 未声明的标识符
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(306): error C2039: "GetEntityManager": 不是 "UMassEntitySubsystem" 的成员
1>E:\engine\Engine\Plugins\Runtime\MassGameplay\Source\MassSpawner\Public\MassEntityTemplateRegistry.h(14): note: 参见“UMassEntitySubsystem”的声明
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Misc\MSBPFunctionLibrary.cpp(326): error C2065: “EntityManager”: 未声明的标识符
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Processors\MSHashGridProcessor.h(37): error C2061: 语法错误: 标识符“FMassEntityManager”
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Processors\MSHashGridProcessor.h(37): error C3668: “UMSHashGridProcessor::Execute”: 包含重写说明符“override”的方法没有重写任何基类方法
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Processors\MSHashGridProcessor.h(37): warning C4263: “void UMSHashGridProcessor::Execute(void)”: 成员函数不重写任何基类虚拟成员函数
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Processors\MSHashGridProcessor.h(38): warning C4264: “void UMassProcessor::Execute(UMassEntitySubsystem &,FMassExecutionContext &)”: 不重写基“UMassProcessor”中的虚拟成员函数；函数被隐藏
1>E:\engine\Engine\Plugins\Runtime\MassEntity\Source\MassEntity\Public\MassProcessor.h(91): note: 参见“UMassProcessor::Execute”的声明
1>E:\engine\Engine\Plugins\Runtime\MassEntity\Source\MassEntity\Public\MassExecutor.h(14): note: 参见“UMassProcessor”的声明
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Processors\MSHashGridProcessor.h(56): error C2061: 语法错误: 标识符“FMassEntityManager”
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Processors\MSHashGridProcessor.h(56): error C3668: “UMSHashGridMemberInitializationProcessor::Execute”: 包含重写说明符“override”的方法没有重写任何基类方法
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Processors\MSHashGridProcessor.h(56): warning C4263: “void UMSHashGridMemberInitializationProcessor::Execute(void)”: 成员函数不重写任何基类虚拟成员函数
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Processors\MSHashGridProcessor.h(58): warning C4264: “void UMassProcessor::Execute(UMassEntitySubsystem &,FMassExecutionContext &)”: 不重写基“UMassProcessor”中的虚拟成员函数；函数被隐藏
1>E:\engine\Engine\Plugins\Runtime\MassEntity\Source\MassEntity\Public\MassProcessor.h(91): note: 参见“UMassProcessor::Execute”的声明
1>E:\engine\Engine\Plugins\Runtime\MassEntity\Source\MassEntity\Public\MassExecutor.h(14): note: 参见“UMassProcessor”的声明
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Processors\MSHashGridProcessor.cpp(28): error C2039: "RegisterWithProcessor": 不是 "FMassEntityQuery" 的成员
1>E:\engine\Engine\Plugins\Runtime\MassEntity\Source\MassEntity\Public\MassEntitySubsystem.h(17): note: 参见“FMassEntityQuery”的声明
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Processors\MSHashGridProcessor.cpp(32): error C2065: “FMassEntityManager”: 未声明的标识符
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Processors\MSHashGridProcessor.cpp(32): error C2065: “EntitySubsystem”: 未声明的标识符
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Processors\MSHashGridProcessor.cpp(32): error C2065: “Context”: 未声明的标识符
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Processors\MSHashGridProcessor.cpp(32): error C2275: “FMassExecutionContext”: 将此类型用作表达式非法
1>E:\engine\Engine\Plugins\Runtime\MassEntity\Source\MassEntity\Public\MassEntitySubsystem.h(408): note: 参见“FMassExecutionContext”的声明
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Processors\MSHashGridProcessor.cpp(32): error C2761: “void UMSHashGridProcessor::Execute(void)”: 不允许重新声明成员
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Processors\MSHashGridProcessor.cpp(33): error C2143: 语法错误: 缺少“;”(在“{”的前面)
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Processors\MSHashGridProcessor.cpp(33): error C2447: “{”: 缺少函数标题(是否是老式的形式表?)
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Processors\MSHashGridProcessor.cpp(67): error C2039: "RegisterWithProcessor": 不是 "FMassEntityQuery" 的成员
1>E:\engine\Engine\Plugins\Runtime\MassEntity\Source\MassEntity\Public\MassEntitySubsystem.h(17): note: 参见“FMassEntityQuery”的声明
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Processors\MSHashGridProcessor.cpp(71): error C2065: “FMassEntityManager”: 未声明的标识符
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Processors\MSHashGridProcessor.cpp(71): error C2065: “EntitySubsystem”: 未声明的标识符
1>E:\workspace\UE4\MassSample\Plugins\MassCommunitySample\Source\MassCommunitySample\Common\Processors\MSHashGridProcessor.cpp(71): fatal error C1003: 错误计数超过 100；正在停止编译

**Comment by Megafunk** [comment]
The project's main branch currently only supports UE 5.1 p 2 (released 5.1 soon)
The biggest change:
`UMassEntitySubsystem `became a struct called `FMassEntityManager`
You could try the https://github.com/Megafunk/MassSample/tree/5.0 tagged release if you need 5.0.3 support.
