### ISSUE TITLE
MEC_InterpMovingCubeActorRepresentation could be simplified.

### ISSUE THREAD

**Issue by error454** [Megafunk/MassSample#51]
The trait configuration for `MEC_InterpMovingCubeActorRepresentation` looks like this.
<img width="323" alt="image" src="https://user-images.githubusercontent.com/700435/226208156-4a6f01ca-c266-4bfe-9a14-6506f76453a5.png">

I believe that Index 2 can be deleted as there aren't any processors that query for that archetype.

Index 0: LOD
index 1: Visuals
Index 2: ????
Index 3: Interp Movement
Index 4: Visualization dependency

**Comment by Megafunk** [comment]
Removed the goofed extra fragment list there, thanks!!!

![image](https://github.com/Megafunk/MassSample/assets/6806463/c8bea3b1-178f-454b-9ec8-d9124e2a6314)

**Comment by Megafunk** [comment]
Also... I am starstruck someone from skookumscript is looking at our Repo... Thanks for checking it out! 🥺
